apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: "abc@abc.com"
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "postgres"
  nodeSelector:
    disktype: ssd